GET http://localhost:5001/conflux-bacaa/us-central1/api/0NyxKqBtD37vYqLlkDfa/spaces
Content-Type: application/json

###

POST http://localhost:5001/conflux-bacaa/us-central1/api/0NyxKqBtD37vYqLlkDfa/spaces
Content-Type: application/json

{
   "createdBy": "1234ABCD",
   "item": {
      "active": true,
      "description": "",
      "icon": "folder_open",
      "id": "34_fame",
      "key": "34_fame",
      "name": "34 Fame",
      "overview": "# Overview",
      "private": false,
      "starred": true
   }
}

###
